# Generated by Django 4.1.6 on 2023-02-17 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("terminal", "0003_human_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="human_ptr",
        ),
        migrations.DeleteModel(
            name="Human",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
