# Generated by Django 4.1.6 on 2023-02-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("terminal", "0005_human_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("img", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Human",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.AddField(
            model_name="image",
            name="poll",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="terminal.poll"),
        ),
    ]
